name: push_developpement

on:
  push:
    branches: [ master ]

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm ci
    - run: npm run test
    - run: echo "End unit tests"


  quality_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
    - run: echo "End quality tests"
    
  
  security_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          crda: latest
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
      - run: echo "End security tests"

  build: 
    runs-on: ubuntu-latest
    needs: [unit_tests, quality_tests, security_tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - name: Archive Dev Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: 
      - run: echo "End build"

  discord_notification:
    name: Envoi d'une notification Discord
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: ""

  finish:
    runs-on: ubuntu-latest
    needs: discord_notification
    steps:
      - run: echo "Pipeline finished"

