name: push_developpement

on:
  push:
    branches: [ master ]

jobs:
  build_dev:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Npm install
      run: npm install
    - run: npm run test
    - run: echo "Fin"